cmu-delphi/epidatr

.Rbuildignore
Change "^\Makefile$" -> "^Makefile$" (remove backslash)
=> Fix typo in .Rbuildignore blocking doc&install

R/check.R, R/constants.R, R/covidcast.R, R/epidatacall.R, R/model.R, R/parse.R, R/request.R, R/utils.R
=> Minor lints 

R/endpoints.R
Fixes #21. Fixes #19. Relied on a bad usage of `ifelse`, which doesn't do what one would think.
=> Fix `pvt_twitter` and `wiki` fetch_classic bug

README.md
This is step i. of the rename [here](https://github.com/cmu-delphi/delphi-epidata-r/issues/31#issuecomment-1195732206).  Step ii. is already done with the creation of the branch that this PR is based off of.  Steps iii. onward will remain TODO afterward.
=> Add rename notice to README.md, remove non-working CRAN install cmd

R/constants.R
- Rename `delphi_epidata` -> `epidatr`
- Add slash between package name and version, to match epidatpy's format for
User-Agent (and the convention for specifying versions in User-Agent)
=> Apply rename and slightly adjust format of User-Agent

README.md, man/covid_hosp_facility_lookup.Rd, man/fluview_clinical.Rd, vignettes/covidcast.Rmd, vignettes/epidatr.Rmd
it's better to use remotes since it has fewer dependencies than devtools
=> change from devtools to remotes for install instructions.

R/constants.R
see https://github.com/cmu-delphi/delphi-epidata/pull/1164
=> update base url to reference `api.covidcast.cmu.edu/epidata`

R/constants.R
follow-up to #103
approvals are very welcome, but this should not be merged until we have a new cert installed for api.delphi.cmu.edu. (PR is in draft status to prevent accidental merging.)
=> update base url to `api.delphi.cmu.edu`

.Rbuildignore, .gitignore, R/endpoints.R, man/covid_hosp_facility_lookup.Rd, man/covidcast.Rd, man/covidcast_meta.Rd, man/delphi.Rd, man/dengue_nowcast.Rd, man/fluview_meta.Rd, man/kcdc_ili.Rd, man/pvt_cdc.Rd, man/pvt_dengue_sensors.Rd, man/pvt_ght.Rd, man/pvt_meta_norostat.Rd, man/pvt_norostat.Rd, vignettes/covidcast.Rmd, vignettes/endpoints.Rmd
See #102 for actual discussion, this should be ready to merge as is.
=> first pass endpoints vignette (for closing #96) (take 2)

README.md
realized we hadn't documented the keys in the readme. doing that
=> docs: add links to API key registration

R/check.R, R/epidatacall.R, R/utils.R, man/assert_character_param.Rd, man/assert_date_param.Rd, man/assert_integerish_param.Rd, man/epidata_call.Rd
closes #108 
In the process of doing this, I noticed that the [epidata_call](https://cmu-delphi.github.io/epidatr/reference/epidata_call.html) docs are in a weird state. On the [reference page](https://cmu-delphi.github.io/epidatr/reference/index.html), there's a mass of functions all together `create_epidata_call() fetch() fetch_tbl() fetch_classic() request_url() with_base_url() ` which point at that page. Several of these are internal only, and some were actually moved from external to strictly internal. The second commit in the pull request may deal with that
=> Internals docs

vignettes/endpoints.Rmd
`pvt_norostat`'s locations are a bit unusual. This gives at least one functional example. Ideally we'd also point at a full list of the locations, but as per https://github.com/cmu-delphi/delphi-epidata/issues/1209 there isn't such a public list atm
=> docs: actual example for `pvt_norostat`

R/covidcast.R, R/epidatacall.R, R/request.R, man/covidcast_epidata.Rd, man/do_request.Rd, man/epidata_call.Rd, man/request_impl.Rd, tests/testthat/test-epidatacall.R, vignettes/endpoints.Rmd
Adds two parameters to several functions:
- `timeout_seconds` gives the maximum time before a connection will time out. Default is 30 seconds, which matches the value returned in the call below (can't find documentation for httr's default, since it clearly isn't using [libcurl's](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html)). Originally motivated by
```
chng_outpatient <- epidatr::covidcast(
data_source = "chng", signals = "smoothed_adj_outpatient_covid",
geo_type = "state",
time_type = "day",
time_values = "*",
geo_values = "*",
issues = epirange("2020-11-16","2021-03-16")
) %>% fetch()
```
which returns a timeout message, trying 3 times. A working version in this branch is
```
chng_outpatient <- epidatr::covidcast(
data_source = "chng", signals = "smoothed_adj_outpatient_covid", …
```
=> Extreme requests

.github/workflows/pkgdown.yaml
I'd rather pkgdown stopped trying to run on my fork causing failing build notifications. This should solve it, taken from [here](https://github.com/orgs/community/discussions/26409)
=> CI: stop building pkgdown on forks

vignettes/epidatr.Rmd
(if you want quidel COVID tests you have to get it from the covidcast endpoint)
=> Quidel endpoint only serves flu data

.github/workflows/ci.yml, .github/workflows/document.yaml, .github/workflows/lint.yaml, .github/workflows/style.yaml
=> Improve CI

.bumpversion.cfg, DESCRIPTION, NEWS.md, R/constants.R, R/request.R, man/get_api_key.Rd
fix for #177, and a corresponding version bump
=> fix+chore: version bump, fix #177

R/cache.R, man/get_api_key.Rd
fix #188 
since the default for [max_size in cache_disk](https://cachem.r-lib.org/reference/cache_disk.html) is `1024 * 1024^2`, a double, that argument can eat doubles, so remove the `as.integer` cast that's overflowing
=> fix: cache size integer overflow

.Rbuildignore, LICENSE, LICENSE.md
Following R conventions on the owners, as its ambiguous which orgs exactly would hold. Also adding the particular rights claimed...
=> fix: actual license details

R/cache.R, man/clear_cache.Rd, man/get_api_key.Rd
minor fix for if someone calls `clear_cache(someDir)` to reset the cache, rather than `clear_cache(dir = someDir)`
=> fix: order of args in `clear_cache` positional bugs

.github/workflows/pkgdown.yaml
Website wasn't updating because workflow never triggered.
=> Deploy docs website on push/pull to `dev`, since we don't have a `main` branch

R/covidcast.R, R/endpoints.R, R/epidatacall.R, _pkgdown.yml, man/covidcast_epidata.Rd, man/epidata_call.Rd, man/get_api_key.Rd
Low-hanging fruit from https://github.com/cmu-delphi/epidatr/issues/212
Closes https://github.com/cmu-delphi/epidatr/issues/205
=> Simple documentation fixes

.github/workflows/pkgdown.yaml, DESCRIPTION, DEVELOPMENT.md, _pkgdown.yml
https://github.com/cmu-delphi/epidatr/pull/213 keeps the doc website updated, but it matches `dev` rather than any CRAN release. If people go from CRAN to our documentation, they're going to see docs for a version they don't have. However, we'd also like to be able to see a preview of the `dev` version of the docs.
`pkgdown` lets you build doc websites from [both releases and development branches](https://pkgdown.r-lib.org/reference/build_site.html#development-mode). This PR turns on that feature, and publishes the doc site on push/pull to both `main` (reinstated to commit https://github.com/cmu-delphi/epidatr/commit/0adb796a54aee22cc54f9e1d0a724492892267b9, when [`CRAN-SUBMISSION`](https://github.com/cmu-delphi/epidatr/blob/dev/CRAN-SUBMISSION) was changed last) and `dev`. The `dev` site …
=> Support public and dev docs site

R/endpoints.R, R/epidatacall.R, tests/testthat/test-endpoints.R
=> Check that endpoint `...` are empty

R/avail_endpoints.R, R/endpoints.R, man/pub_covid_hosp_facility.Rd, man/pub_covid_hosp_facility_lookup.Rd, man/pub_covid_hosp_state_timeseries.Rd, man/pub_covidcast.Rd, man/pub_delphi.Rd, man/pub_dengue_nowcast.Rd, man/pub_ecdc_ili.Rd, man/pub_flusurv.Rd, man/pub_fluview.Rd, man/pub_fluview_clinical.Rd, man/pub_fluview_meta.Rd, man/pub_gft.Rd, man/pub_kcdc_ili.Rd, man/pub_meta.Rd, man/pub_nidss_dengue.Rd, man/pub_nidss_flu.Rd, man/pub_nowcast.Rd, man/pub_paho_dengue.Rd, man/pub_wiki.Rd, man/pvt_cdc.Rd, man/pvt_dengue_sensors.Rd, man/pvt_ght.Rd, man/pvt_meta_norostat.Rd, man/pvt_norostat.Rd, man/pvt_sensors.Rd, man/pvt_twitter.Rd
Clarify data source, region, and what types of diseases and signals are available. Add message that most data is US only.
=> Add more detail to `avail_endpoint` descriptions

R/endpoints.R
Because of the switch in https://github.com/cmu-delphi/epidatr/pull/223 to using `as.Date(tryFormats = ...)` instead of `as.Date(format = ...)`, failed parsing behavior has changed. Now if a value doesn't match any of the provided formats, `as.Date` errors.
This has caused `pub_fluview_meta` to start failing. One of the fields is in YYYYWW (epiweek) format, but was being parsed as a date. Presumably with the old code, this was always being replaced with NA when the parsing failed. Ask for it to be formatted as an epiweek instead.
=> lastest_issue is an epiweek, not a date

R/utils.R, tests/testthat/test-utils.R
Closes [#192](https://github.com/cmu-delphi/epidatr/issues/192) and #194.
When `as_of` or `issues` is provided a Date, the comparison `as_of != "*"` tries and fails to convert "\*" to a Date also so it can do the comparison. Instead, use `identical`, which doesn't try to implicitly convert the "\*".
=> Support version params `as_of` and `issues` passed as Date objects

DESCRIPTION, README.Rmd, README.md, vignettes/epidatr.Rmd, vignettes/signal-discovery.Rmd, vignettes/versioned-data.Rmd
- Add more descriptive info to landing page
- Add citation and licensing info to landing page
- Move installation, setup, and basic usage from landing page to intro vignette
- Move signal discovery and example "other" endpoint calls from intro vignette to new signal discovery vignette
- Add geo info to intro vignette
- Add examples of geo specification to intro vignette
- Add examples of `as_of` specification to intro vignette
- Add stub versioned data vignette
Partially addresses https://github.com/cmu-delphi/epidatr/issues/212
=> Redo landing page and intro doc

R/model.R, man/covidcast_epidata.Rd, tests/testthat/test-model.R
Some values (e.g. 2542264861) returned by `pub_wiki` are being coerced to NA [here](https://github.com/cmu-delphi/epidatr/blob/ff68c4551aaf375c7b7a5fe4621f16ae24eed2be/R/model.R#L159) because they exceed R's int storage capacity.
=> Parse int fields as double so large values don't get set to NA

NEWS.md, R/endpoints.R, man/pub_wiki.Rd, man/pvt_twitter.Rd, tests/testthat/test-endpoints.R, vignettes/signal-discovery.Rmd
`pvt_twitter` and `pub_wiki` can take dates in either day or week format. These are provided as separate, mutually exclusive (will fail) params `dates` and `epiweeks`. This format disagrees with the interface for `pub_covidcast`, which also supports days and weeks. Change the twitter and wiki interfaces to match, with new params `time_type` and `time_values`.
This also makes supporting the date range default to wildcard "\*" (all dates) easier -- if both `dates` and `epiweeks` params were set to "\*" by default, the user would have to specify which date type they wanted to use anyway, a la `time_type`, since we wouldn't be able to automatically determine precedence.
=> Combine timetype wiki twitter

README.Rmd, README.md
Incorporating feedback from [here](https://github.com/cmu-delphi/www-main/pull/912).
=> doc: update readme with blog post feedback

.github/pull_request_template.md, DESCRIPTION, DEVELOPMENT.md, NEWS.md
- Change version number to 1.0.1 ("first PR" of 1.0.0)
- Change the news heading from 1.0.0.9000 to 1.1.0 (next release version)
=> repo+doc: follow version conventions from epiprocess

.github/workflows/pkgdown.yaml, .gitignore, _pkgdown.yml
Header bar text is unreadable on [epidatr/dev](https://cmu-delphi.github.io/epidatr/dev/) docs, fix by matching the settings in `_pkgdown.yml` with the [settings in epipredict ](https://github.com/cmu-delphi/epipredict/blob/dev/_pkgdown.yml), which [look correct](https://cmu-delphi.github.io/epipredict/). I tested this locally with: `build_home_index(); init_site()` and then `python -m http.server` to host.
Also matches the pkgdown ci with how it's done in epiprocess (based on branch instead of .9000 version numbers).
=> ci+docs: match style with epipredict

.github/pull_request_template.md, .github/workflows/document.yaml, DESCRIPTION, NEWS.md, R/cache.R, R/epidatacall.R, R/request.R, man/clear_cache.Rd, man/do_request.Rd, man/fetch_args_list.Rd, man/request_impl.Rd, man/set_cache.Rd, tests/testthat/generate_test_data.R, tests/testthat/test-epidatacall.R, tests/testthat/test-request.R
Use `rappdirs::user_cache_dir("R", version = "epidatr")` instead of `tools::R_user_dir("epidatr")` ([previous discussion](https://github.com/cmu-delphi/epidatr/issues/181#issuecomment-1745458917)).
Also informs the user of the cache and its variables when its used, e.g.:
```r
! epidatr cache is being used (set env var EPIDATR_USE_CACHE=FALSE if not intended).
ℹ The cache directory is ~/.cache/R/epidatr.
ℹ The cache will be cleared after 1 days and will be pruned if it exceeds 1024 MB.
ℹ The log of cache transactions is stored at ~/.cache/R/epidatr/logfile.txt.
```
=> fix: make default cache directory R version portable

.github/workflows/document.yaml
Please:
PR).
- [NA] Makes sure to bump the version number in `DESCRIPTION`. Always increment
- [NA] Describe changes made in NEWS.md, making sure breaking changes
we're also building the docs using `README.rmd`. But the docs gh action didn't add the readme as a man page. This fixes that.
=> CI: docs also includes the readme

.github/workflows/R-CMD-check.yaml, .github/workflows/document.yaml, .github/workflows/lint.yaml, .github/workflows/style.yaml, README.Rmd, README.md
Please:
PR).
Some more CI fixes, see commits.
=> ci: document readme and add trigger buttons to all actions

DESCRIPTION, NEWS.md, R/utils.R, tests/testthat/test-utils.R
Please:
PR).
If `as_of` sent to `check_is_recent` is a `Date`, compare to a `Date` threshold.
Closes https://github.com/cmu-delphi/epidatr/issues/258
=> If `as_of` sent to `check_is_recent` is a `Date`, compare to a `Date` threshold.

.github/workflows/pkgdown.yaml, R/utils.R, _pkgdown.yml
Please:
PR).
CI seems to be misbehaving and we're getting the `dev` branch docs on the main page. Try to fix with [Github variables](https://docs.github.com/en/actions/learn-github-actions/variables) instead of [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts).
=> ci: fix pkgdown

DESCRIPTION, NEWS.md, R/endpoints.R, man/pub_covidcast.Rd, tests/testthat/test-endpoints.R
Please:
PR).
`missing` doesn't count default values as non-missing. If a user doesn't pass `geo_values` or `time_values` (both of which default to "*" in `pub_covidcast`), or `dates` (in `pub_covid_hosp_state_timeseries`), the `missing` check fails. To avoid this, just don't check missingness of those two arguments.
=> Turn off endpoint missing checks for `geo_values` and `time_values`, which have defaults

DESCRIPTION, NEWS.md, R/epidatr-package.R
Please:
PR).
`EPIDATR_USE_CACHE` only supported exactly "TRUE" before. Now it supports all logical values and includes a warning when any value that can't be converted to logical is provided.
=> fix: improve reading of `EPIDATR_USE_CACHE` variable

DESCRIPTION, R/model.R
Please:
PR).
Support more date formats in function to convert dates to epiweeks. Use `parse_api_date` since it already supports both common formats.
=> Support "YYYY-MM-DD" format in `date_to_epiweek`

DESCRIPTION, DEVELOPMENT.md, NEWS.md, tests/testthat/test-cache.R
Please:
PR).
covering the NEWS problems, version bump, just a couple of minor test additions
=> minor test fixes, NEWS, dev link borked

vignettes/epidatr.Rmd
Please:
PR).
number (the second number).~~
1.7.2, then write your changes under the 1.8 heading).~~
Found some strange wording in the migration to epidatpy. It helps to read the [section in context](https://cmu-delphi.github.io/epidatr/articles/epidatr.html#basic-usage) to see that it gets weird (Ctrl + F "We can also request data for a single location at a time").
=> docs: improve strange wording on getting started page

DESCRIPTION, R/endpoints.R, README.md, man/covidcast_epidata.Rd, man/pub_covid_hosp_facility.Rd, man/pvt_norostat.Rd
=> Audited examples in endpoint.r, see TODO items for further edits needed.

.github/workflows/test-coverage.yml, .lintr, DESCRIPTION, NEWS.md, R/covidcast.R, man/covidcast_epidata.Rd
=> Fixing #300 by giving default values for fields

.github/workflows/R-CMD-check-full.yaml
Please:
PR).
CI update to make sure we test 3.5 on all systems (earliest version we claim to support).
=> ci: consistently test R 3.5 across platforms
